// AUTOGENERATED by apps/web/scripts/capture-shots.mjs — do not edit by hand.
// Real product screenshots of the running Loonext app with seeded demo data
// ("Mike's Plumbing"). Re-run the capture script to regenerate. Each entry is a
// pre-sized WebP (with an AVIF sibling at the same path) plus intrinsic
// width/height (zero-CLS) and a tiny blurred placeholder data-URI (blur-up).
//
// Usage (VISUALS §5): render inside <Frame variant="browser|phone">, set the
// <img> width/height from the entry, loading="lazy" + decoding="async" below
// the fold, and use `placeholder` as the blur-up background.

export type Shot = {
  /** Path under /public — the WebP. Swap the extension for the AVIF sibling. */
  readonly src: string;
  /** Path under /public — the AVIF sibling at the same display size. */
  readonly avif: string;
  /** Intrinsic display width in CSS px (raster is exactly this wide). */
  readonly width: number;
  /** Intrinsic display height in CSS px (set both to avoid layout shift). */
  readonly height: number;
  /** Blurred low-res placeholder as a base64 data-URI (blur-up). */
  readonly placeholder: string;
  /** Honest alt text describing the real screen. */
  readonly alt: string;
  /** "light" | "dark" — pair the two per surface for theme-correct rendering. */
  readonly theme: "light" | "dark";
  /** Device framing the shot expects: "browser" (desktop) or "phone" (mobile). */
  readonly frame: "browser" | "phone";
};

export const shots = {
  "inbox-list-light": {
    src: "/shots/inbox-list-light.webp",
    avif: "/shots/inbox-list-light.avif",
    width: 1200,
    height: 750,
    theme: "light",
    frame: "browser",
    alt: "Loonext shared inbox showing a list of customer text conversations with New, Open, Waiting and Closed statuses, unread markers and an assignee avatar.",
    placeholder: "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAACwAQCdASoUAA0AA4BaJZwAA7wJvcIAAP70fAX7mtQcdvZXiGbqyIAA",
  },
  "inbox-list-dark": {
    src: "/shots/inbox-list-dark.webp",
    avif: "/shots/inbox-list-dark.avif",
    width: 1200,
    height: 750,
    theme: "dark",
    frame: "browser",
    alt: "Loonext shared inbox showing a list of customer text conversations with New, Open, Waiting and Closed statuses, unread markers and an assignee avatar.",
    placeholder: "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACwAgCdASoUAA0ALrV2u12jqampiYC0SzgAB3gSz/AA/vLAy5M3yPRurHVcHowX341AAA==",
  },
  "thread-open-light": {
    src: "/shots/thread-open-light.webp",
    avif: "/shots/thread-open-light.avif",
    width: 1200,
    height: 750,
    theme: "light",
    frame: "browser",
    alt: "An open customer conversation in Loonext with inbound and outbound texts, a photo the customer sent, an internal team note, delivery states, and one message marked done.",
    placeholder: "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAABQAwCdASoUAA0APu1iqk2ppaQiMAgBMB2JZwAAW+jCRd7sAAD+8c+DKvRnCFi75Z+23+XsN8SyoZe5c0wjt8OFx+wfyDBDdgYxD6UT9ZMbAzAA",
  },
  "thread-open-dark": {
    src: "/shots/thread-open-dark.webp",
    avif: "/shots/thread-open-dark.avif",
    width: 1200,
    height: 750,
    theme: "dark",
    frame: "browser",
    alt: "An open customer conversation in Loonext with inbound and outbound texts, a photo the customer sent, an internal team note, delivery states, and one message marked done.",
    placeholder: "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACQAwCdASoUAA0APu1kqk4ppaQiMAgBMB2JZwAAW+j/Bmg3BmAAAP7r83f76SDGqii1erb9WFg+YKmkHnFNSbQXndKYS+9tMqarkOPeBeAAAA==",
  },
  "contact-panel-light": {
    src: "/shots/contact-panel-light.webp",
    avif: "/shots/contact-panel-light.avif",
    width: 1200,
    height: 750,
    theme: "light",
    frame: "browser",
    alt: "A Loonext conversation with the contact details panel open, showing the customer's name, number, consent record, address and notes beside the message thread.",
    placeholder: "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAwAwCdASoUAA0APu1iqU2ppaQiMAgBMB2JZwAAXAXK+IAgAP7xz0n93o+hiRR0Y8Jkp70N/BbrvVS8yS2/Zrv24sXQyBCkMHAAAA==",
  },
  "contact-panel-dark": {
    src: "/shots/contact-panel-dark.webp",
    avif: "/shots/contact-panel-dark.avif",
    width: 1200,
    height: 750,
    theme: "dark",
    frame: "browser",
    alt: "A Loonext conversation with the contact details panel open, showing the customer's name, number, consent record, address and notes beside the message thread.",
    placeholder: "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAQAwCdASoUAA0APu1iqU2ppaQiMAgBMB2JZQAAeuwSQAAA/u/I8HxeQl7wBKUmWbEosM6pxPH9hQmJtkaoMP9VXb38LNuAAAA=",
  },
  "mobile-inbox-light": {
    src: "/shots/mobile-inbox-light.webp",
    avif: "/shots/mobile-inbox-light.avif",
    width: 390,
    height: 844,
    theme: "light",
    frame: "phone",
    alt: "The Loonext inbox on a phone: a full-screen list of customer text conversations with statuses and unread markers, sized for one-handed use.",
    placeholder: "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAAAwBACdASoUACsAPu1eqU2ppKQiMBqqqTAdiWkAAFNRiudCAodRXEErwgAA/vCBLddsZgbZaGO4TO2jUZu610CjxaMtZMgLBJRhQUVw6p1PNaPQ20VS+xYe5ZUW6rQDtiS1qGGz6+t0ppCJzrlLSipxJeSz2vT/WZgivBgBYCBDePE/lQAAAA==",
  },
  "mobile-inbox-dark": {
    src: "/shots/mobile-inbox-dark.webp",
    avif: "/shots/mobile-inbox-dark.avif",
    width: 390,
    height: 844,
    theme: "dark",
    frame: "phone",
    alt: "The Loonext inbox on a phone: a full-screen list of customer text conversations with statuses and unread markers, sized for one-handed use.",
    placeholder: "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAABwBACdASoUACsAPuVYp02pJKOiNVv4ASAciWcA0BgwHfqv1huLrBi2ZzWQAAD+8EEiq5+BLxj/0XG+0kBnAHyuTfARuuRmBw466ycxe/oL5HOkDMUlMRnrKl6Ald+GHkQaAg9Fosa71gD7+37nvavyIMHLBE/6ziNyTaiu9n6u4WRPPQTmCwlLpYUy2HEa/P5UAA==",
  },
  "mobile-thread-light": {
    src: "/shots/mobile-thread-light.webp",
    avif: "/shots/mobile-thread-light.avif",
    width: 390,
    height: 844,
    theme: "light",
    frame: "phone",
    alt: "A customer text conversation on a phone in Loonext, showing inbound and outbound messages, a photo, and delivery states in a full-screen thread.",
    placeholder: "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAABwBACdASoUACsAPu1iqE2ppaOiMAgBMB2JZQDI1B4XW23u55ul+dYA8uA6AAD+8eCjR9VMCXwYzJqDXl1OhoVKp90eD3PllzjsatQYI3DtAJcYlonOixqNmVrC+xkVnZWB6dmAu4FuZOGk5x/2zPlnZgaC2maCMhfjXbEYR+2bN+2iSFzSEzEfSPguhXP8bD9d38cnehcxrNoUkAAAAA==",
  },
  "mobile-thread-dark": {
    src: "/shots/mobile-thread-dark.webp",
    avif: "/shots/mobile-thread-dark.avif",
    width: 390,
    height: 844,
    theme: "dark",
    frame: "phone",
    alt: "A customer text conversation on a phone in Loonext, showing inbound and outbound messages, a photo, and delivery states in a full-screen thread.",
    placeholder: "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAAAQBgCdASoUACsAPulmo02pJiMiMBqtUSAdCWUA0MwWU33vgandlmmeq4OfzH87O1RjcHCn/LOT1QAA/u6dHy0XmmaODzjtAV0kQW//8Lye7pSiXeAdYFQ8Oo1ZS+pRxj5u5i9e97LGP2AyRUy33xjK/kzSdD3IkhiigCy251oLVd4pi1gDYXlgDouGSRDiAVdzvxCZ6KZ56CnIAAA=",
  },
  "onboarding-setting-up-light": {
    src: "/shots/onboarding-setting-up-light.webp",
    avif: "/shots/onboarding-setting-up-light.avif",
    width: 1200,
    height: 750,
    theme: "light",
    frame: "browser",
    alt: "The Loonext onboarding screen the moment a new business number is revealed, in 36-point type with a copy button, above a checklist confirming the number is live and the inbox is ready.",
    placeholder: "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACwAgCdASoUAA0APu1iqU2ppaOiMAgBMB2JaQAAeyAA/vCo7agIMQ81yAAAAA==",
  },
  "onboarding-setting-up-dark": {
    src: "/shots/onboarding-setting-up-dark.webp",
    avif: "/shots/onboarding-setting-up-dark.avif",
    width: 1200,
    height: 750,
    theme: "dark",
    frame: "browser",
    alt: "The Loonext onboarding screen the moment a new business number is revealed, in 36-point type with a copy button, above a checklist confirming the number is live and the inbox is ready.",
    placeholder: "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAgCdASoUAA0APu1iqU2ppaOiMAgBMB2JaQAAe/QAAP7woeBn38qPPAERT4hu80KAAA==",
  },
} as const satisfies Record<string, Shot>;

export type ShotKey = keyof typeof shots;

/** All shots for a surface id, keyed by theme (e.g. shotPair("inbox-list")). */
export function shotPair(id: string): { light?: Shot; dark?: Shot } {
  const pair: { light?: Shot; dark?: Shot } = {};
  for (const shot of Object.values(shots)) {
    if (shot.src.includes(`/${id}.`) || shot.src.includes(`/${id}-`)) {
      pair[shot.theme] = shot;
    }
  }
  return pair;
}
