// AUTOGENERATED by apps/web/scripts/capture-shots.mjs — do not edit by hand.
// Real product screenshots of the running Loonext app with seeded demo data
// ("Mike's Plumbing"). Re-run the capture script to regenerate. Each entry is a
// pre-sized WebP (with an AVIF sibling at the same path) plus intrinsic
// width/height (zero-CLS) and a tiny blurred placeholder data-URI (blur-up).
//
// Usage (VISUALS §5): render inside <Frame variant="browser|phone">, set the
// <img> width/height from the entry, loading="lazy" + decoding="async" below
// the fold, and use `placeholder` as the blur-up background.

export type Shot = {
  /** Path under /public — the WebP. Swap the extension for the AVIF sibling. */
  readonly src: string;
  /** Path under /public — the AVIF sibling at the same display size. */
  readonly avif: string;
  /** Intrinsic display width in CSS px (raster is exactly this wide). */
  readonly width: number;
  /** Intrinsic display height in CSS px (set both to avoid layout shift). */
  readonly height: number;
  /** Blurred low-res placeholder as a base64 data-URI (blur-up). */
  readonly placeholder: string;
  /** Honest alt text describing the real screen. */
  readonly alt: string;
  /** "light" | "dark" — pair the two per surface for theme-correct rendering. */
  readonly theme: "light" | "dark";
  /** Device framing the shot expects: "browser" (desktop) or "phone" (mobile). */
  readonly frame: "browser" | "phone";
};

export const shots = {
  "inbox-list-light": {
    src: "/shots/inbox-list-light.webp",
    avif: "/shots/inbox-list-light.avif",
    width: 1200,
    height: 750,
    theme: "light",
    frame: "browser",
    alt: "Loonext shared inbox showing a list of customer text conversations with New, Open, Waiting and Closed statuses, unread markers and an assignee avatar.",
    placeholder: "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAAAwAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JaQAAW+socMwAAP7vv/SupHgAAA==",
  },
  "inbox-list-dark": {
    src: "/shots/inbox-list-dark.webp",
    avif: "/shots/inbox-list-dark.avif",
    width: 1200,
    height: 750,
    theme: "dark",
    frame: "browser",
    alt: "Loonext shared inbox showing a list of customer text conversations with New, Open, Waiting and Closed statuses, unread markers and an assignee avatar.",
    placeholder: "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAAAwAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JaQAAW+so6CcAAP7ul6gtGLXCsAAA",
  },
  "thread-open-light": {
    src: "/shots/thread-open-light.webp",
    avif: "/shots/thread-open-light.avif",
    width: 1200,
    height: 750,
    theme: "light",
    frame: "browser",
    alt: "An open customer conversation in Loonext with inbound and outbound texts, a photo the customer sent, an internal team note, delivery states, and one message marked done.",
    placeholder: "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAABQAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JaQAAW+n9uIx5AAD+78K2uvgpe+B1ptjat4gU3JAgbOAA",
  },
  "thread-open-dark": {
    src: "/shots/thread-open-dark.webp",
    avif: "/shots/thread-open-dark.avif",
    width: 1200,
    height: 750,
    theme: "dark",
    frame: "browser",
    alt: "An open customer conversation in Loonext with inbound and outbound texts, a photo the customer sent, an internal team note, delivery states, and one message marked done.",
    placeholder: "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACQAwCdASoUAA0APu1iqU2ppaQiMAgBMB2JZ2HgFX/gUIS2iaoAAP7wWU79A01t5VtS/hps4sWLmRakNF1cWyifBEDW1QALTAdCAB6oEgAAAA==",
  },
  "contact-panel-light": {
    src: "/shots/contact-panel-light.webp",
    avif: "/shots/contact-panel-light.avif",
    width: 1200,
    height: 750,
    theme: "light",
    frame: "browser",
    alt: "A Loonext conversation with the contact details panel open, showing the customer's name, number, consent record, address and notes beside the message thread.",
    placeholder: "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAABwAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JaQAAW+qh+DzTAAAA/u+z4/AlXjiiAAAAAA==",
  },
  "contact-panel-dark": {
    src: "/shots/contact-panel-dark.webp",
    avif: "/shots/contact-panel-dark.avif",
    width: 1200,
    height: 750,
    theme: "dark",
    frame: "browser",
    alt: "A Loonext conversation with the contact details panel open, showing the customer's name, number, consent record, address and notes beside the message thread.",
    placeholder: "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAAAwAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JZ19qADcAkeUwAP7wWO4e3P4p1jFYRZNEN4+K0IZ9I9RwAAA=",
  },
  "mobile-inbox-light": {
    src: "/shots/mobile-inbox-light.webp",
    avif: "/shots/mobile-inbox-light.avif",
    width: 390,
    height: 844,
    theme: "light",
    frame: "phone",
    alt: "The Loonext inbox on a phone: a full-screen list of customer text conversations with statuses and unread markers, sized for one-handed use.",
    placeholder: "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAADwBACdASoUACsAPulipk2pJaOiMAqpIB0JZxFAAAHRp5waIkg3RzxG1QSdqiJUhUAA/u/jD5Ibt2q+t1USuclml7MspQo1SoPvFzU9OxldrERvd/Cn+3anxkBLUxz7+gxrm8cax8VwQ3QekZJ7R8K1tIxbCu74NmdwGW7lKczMQHGq+8X+k+RSXE/lQAAA",
  },
  "mobile-inbox-dark": {
    src: "/shots/mobile-inbox-dark.webp",
    avif: "/shots/mobile-inbox-dark.avif",
    width: 390,
    height: 844,
    theme: "dark",
    frame: "phone",
    alt: "The Loonext inbox on a phone: a full-screen list of customer text conversations with statuses and unread markers, sized for one-handed use.",
    placeholder: "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAABwBQCdASoUACsAPu1oqU6ppiOiKqwBMB2JZwAAPZA8rzWihs+V/e5OqAQZ32qMuU8wLzCkAP7w7OwshrwNtYgJQiZVShTlAMInSheKz66menGHiwI4AGKAEA+wPipTLGzRnhcWNdqLh+dY3NpVb/jheWOLFewaKd8wMQDmlO23+hxiAX0Ofb8qDmySlUk/45AcWk45YPwt5PHwJ6AAAA==",
  },
  "mobile-thread-light": {
    src: "/shots/mobile-thread-light.webp",
    avif: "/shots/mobile-thread-light.avif",
    width: 390,
    height: 844,
    theme: "light",
    frame: "phone",
    alt: "A customer text conversation on a phone in Loonext, showing inbound and outbound messages, a photo, and delivery states in a full-screen thread.",
    placeholder: "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAACQBACdASoUACsAPu1kqE2ppaOiMAgBMB2JZwAAhEXuUr5nOibwHtvZ41G5gAAA/vBkASjDUbc2IG4rkW07DnrXrKu9q82RM78TIOxJnx93EXWoZxtLLDbv/rJhMfZTBmrMre0gLjNeBK79fgObAhXEkAqxEAZrNCDnE7suy4I7CtghaAg2GSIAAXD4KgAA",
  },
  "mobile-thread-dark": {
    src: "/shots/mobile-thread-dark.webp",
    avif: "/shots/mobile-thread-dark.avif",
    width: 390,
    height: 844,
    theme: "dark",
    frame: "phone",
    alt: "A customer text conversation on a phone in Loonext, showing inbound and outbound messages, a photo, and delivery states in a full-screen thread.",
    placeholder: "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAABQBgCdASoUACsAPuVkqE2pJiQiNVgIASAciUAaBxVvYACYMXlRVI0EU84NYiMblpU58HaoljtomqTOIAD+8rExSnxPSNvwRI14GFy5QHzPFfK9/5VPcHmFpiYzr/gvdIbaCVi6UHD0sUN2Ge73yzLmjZVPRG5EQbxhZ8XGyxfSM5YEmyBii6WKw8YMAGsDViZOEIVmxuiujHHckuLgAAAA",
  },
  "onboarding-setting-up-light": {
    src: "/shots/onboarding-setting-up-light.webp",
    avif: "/shots/onboarding-setting-up-light.avif",
    width: 1200,
    height: 750,
    theme: "light",
    frame: "browser",
    alt: "The Loonext onboarding screen the moment a new business number is revealed, in 36-point type with a copy button, above a checklist confirming the number is live and the inbox is ready.",
    placeholder: "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAgCdASoUAA0APu1iqU2ppaOiMAgBMB2JaQAAeyAA/vCTzM+79TWqtjO7Q0RwAAA=",
  },
  "onboarding-setting-up-dark": {
    src: "/shots/onboarding-setting-up-dark.webp",
    avif: "/shots/onboarding-setting-up-dark.avif",
    width: 1200,
    height: 750,
    theme: "dark",
    frame: "browser",
    alt: "The Loonext onboarding screen the moment a new business number is revealed, in 36-point type with a copy button, above a checklist confirming the number is live and the inbox is ready.",
    placeholder: "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAgCdASoUAA0APu1iqU2ppaQiMAgBMB2JaQAAe/QAAP7woeBn38qPPAERTr1zi5AAAA==",
  },
} as const satisfies Record<string, Shot>;

export type ShotKey = keyof typeof shots;

/** All shots for a surface id, keyed by theme (e.g. shotPair("inbox-list")). */
export function shotPair(id: string): { light?: Shot; dark?: Shot } {
  const pair: { light?: Shot; dark?: Shot } = {};
  for (const shot of Object.values(shots)) {
    if (shot.src.includes(`/${id}.`) || shot.src.includes(`/${id}-`)) {
      pair[shot.theme] = shot;
    }
  }
  return pair;
}
