import type { MetadataRoute } from "next";

/**
 * PWA web app manifest (DESIGN.md G9), served at /manifest.webmanifest via
 * the Next metadata route (auto-linked in <head>). Installability matters
 * for the truck: standalone display, petrol theme, straight into the inbox.
 *
 * Icons are committed rasters generated by brand/generate.mjs from the
 * double-o brand SVGs (#206, brand/README.md): `any` is the rounded INK
 * tile (brand/loonext-tile-dark.svg, transparent corners kept) - the dark
 * pair is the shipped icon everywhere (founder direction 2026-07-22) -
 * `maskable` is the full-bleed dark variant (brand/loonext-maskable-dark.svg)
 * with the mark inside the 80% safe zone.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Loonext",
    short_name: "Loonext",
    description:
      "One local business number your whole team can text from. Every incoming text becomes a conversation you can reply to, assign, tag, and close.",
    id: "/inbox",
    start_url: "/inbox",
    display: "standalone",
    background_color: "#FAFAF9", // stone-50 (G2 light background)
    theme_color: "#0F766E", // petrol
    orientation: "portrait",
    icons: [
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-maskable-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
