import type { MetadataRoute } from "next";

/**
 * PWA web app manifest (DESIGN.md G9), served at /manifest.webmanifest via
 * the Next metadata route (auto-linked in <head>). Installability matters
 * for the truck: standalone display, petrol theme, straight into the inbox.
 *
 * Icons are committed rasters generated by scripts/generate-icons.mjs from
 * public/icons/loonext-icon.svg — `any` keeps the rounded tile's transparent
 * corners, `maskable` is full-bleed with the glyph inside the safe zone.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Loonext",
    short_name: "Loonext",
    description:
      "One local business number your whole team can text from. Every incoming text becomes a conversation you can reply to, assign, tag, and close.",
    id: "/inbox",
    start_url: "/inbox",
    display: "standalone",
    background_color: "#FAFAF9", // stone-50 (G2 light background)
    theme_color: "#0F766E", // petrol
    orientation: "portrait",
    icons: [
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-maskable-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
