import type { MetadataRoute } from "next";

/**
 * PWA web app manifest (DESIGN.md G9), served at /manifest.webmanifest via
 * the Next metadata route (auto-linked in <head>). Installability matters
 * for the truck: standalone display, petrol theme, straight into the inbox.
 *
 * Icons are committed rasters generated by brand/generate.mjs from the
 * double-o brand SVGs (#206, brand/README.md): `any` is the rounded INK
 * tile (brand/loonext-tile-dark.svg, transparent corners kept) - the dark
 * pair is the shipped icon everywhere (founder direction 2026-07-22) -
 * `maskable` is the full-bleed dark variant (brand/loonext-maskable-dark.svg)
 * with the mark inside the 80% safe zone.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Loonext",
    short_name: "Loonext",
    // #491: the install-prompt copy on the platform this product is actually
    // delivered as ("add it to your home screen"), and it said texting only.
    description:
      "Your business line, shared. Texts and calls land in one inbox the whole crew can answer, assign, turn into a job, and close.",
    id: "/inbox",
    start_url: "/inbox",
    display: "standalone",
    // #362: the splash ground and the chrome both take the page ground, so
    // an installed app opens on the colour it will settle on.
    background_color: "#F3F3EE",
    theme_color: "#F3F3EE",
    orientation: "portrait",
    icons: [
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-maskable-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
