// AUTOGENERATED by apps/web/scripts/build-illustrations.mjs — do not edit by hand.
//
// The JobText marketing illustration set (VISUALS-V2 §3). ONE cohesive library —
// unDraw (undraw.co), MIT-clean license (free commercial use, no attribution
// required, recoloring permitted). Every scene is recolored to the JobText brand
// (petrol accent + warm-stone inks) by the build script, so the whole set reads
// as one art-directed system. Source slugs + license are recorded in
// public/illustrations/CREDITS.md.
//
// Each entry is a branded, optimized inline SVG under /public/illustrations/,
// with its viewBox + intrinsic width/height (for aspect-ratio boxes → zero CLS).
// Render through <Illustration id="..."/> (components/marketing/illustration.tsx).

export type Illustration = {
  /** Path under /public — the branded, optimized SVG. */
  readonly src: string;
  /** SVG viewBox — drives the aspect ratio of the reserved box (zero CLS). */
  readonly viewBox: string;
  /** Intrinsic width in the illustration's own units. */
  readonly w: number;
  /** Intrinsic height in the illustration's own units. */
  readonly h: number;
  /** Honest alt text describing the scene. */
  readonly alt: string;
  /** Source library + slug, for the credits record. */
  readonly credit: string;
};

export const illustrations = {
  "shared-inbox": {
    src: "/illustrations/shared-inbox.svg",
    viewBox: "0 0 960 605",
    w: 960,
    h: 605,
    alt: "A team sharing one conversation — the whole crew sees every customer text.",
    credit: "unDraw · group-chat_nze2 · MIT (undraw.co/license)",
  },
  "get-a-number": {
    src: "/illustrations/get-a-number.svg",
    viewBox: "0 0 633.218 799.931",
    w: 633,
    h: 800,
    alt: "Picking a local business phone number for your area.",
    credit: "unDraw · my-location_dcug · MIT (undraw.co/license)",
  },
  "crew": {
    src: "/illustrations/crew.svg",
    viewBox: "0 0 960 811.159",
    w: 960,
    h: 811,
    alt: "A service crew — everyone on the team, on one shared number.",
    credit: "unDraw · meet-the-team_fau8 · MIT (undraw.co/license)",
  },
  "team-live": {
    src: "/illustrations/team-live.svg",
    viewBox: "0 0 800 645.717",
    w: 800,
    h: 646,
    alt: "A crew replying together in real time from wherever they are.",
    credit: "unDraw · real-time-collaboration_bchs · MIT (undraw.co/license)",
  },
  "canada": {
    src: "/illustrations/canada.svg",
    viewBox: "0 0 960 745.55",
    w: 960,
    h: 746,
    alt: "Finding a local number on a map — coverage across Canada and the US.",
    credit: "unDraw · location-search_9mdg · MIT (undraw.co/license)",
  },
  "compliance-handled": {
    src: "/illustrations/compliance-handled.svg",
    viewBox: "0 0 960 747.646",
    w: 960,
    h: 748,
    alt: "The texting rules, handled — registration and opt-outs taken care of for you.",
    credit: "unDraw · all-checked_d3u6 · MIT (undraw.co/license)",
  },
  "bring-your-number": {
    src: "/illustrations/bring-your-number.svg",
    viewBox: "0 0 739.101 800",
    w: 739,
    h: 800,
    alt: "Forwarding your existing business number to your new JobText number.",
    credit: "unDraw · nfc-sharing_tt2d · MIT (undraw.co/license)",
  },
  "missed-lead": {
    src: "/illustrations/missed-lead.svg",
    viewBox: "0 0 755.916 779.013",
    w: 756,
    h: 779,
    alt: "A customer trying to reach a business — the lead you can't afford to miss.",
    credit: "unDraw · business-call_w1gr · MIT (undraw.co/license)",
  },
  "texting": {
    src: "/illustrations/texting.svg",
    viewBox: "0 0 481.19703 732.37608",
    w: 481,
    h: 732,
    alt: "Texting a business from a phone.",
    credit: "unDraw · messages_okui · MIT (undraw.co/license)",
  },
  "welcome": {
    src: "/illustrations/welcome.svg",
    viewBox: "0 0 505.94587 764.69444",
    w: 506,
    h: 765,
    alt: "Getting set up and welcomed aboard in minutes.",
    credit: "unDraw · welcome-aboard_y4e9 · MIT (undraw.co/license)",
  },
  "data-safe": {
    src: "/illustrations/data-safe.svg",
    viewBox: "0 0 799.468 552.327",
    w: 799,
    h: 552,
    alt: "Your data kept secure — encrypted, never sold.",
    credit: "unDraw · security-on_3ykb · MIT (undraw.co/license)",
  },
} as const satisfies Record<string, Illustration>;

export type IllustrationId = keyof typeof illustrations;

/** Resolve one illustration by id, or undefined if the key is unknown. */
export function getIllustration(id: string): Illustration | undefined {
  return (illustrations as Record<string, Illustration>)[id];
}
