-- ===========================================================================
-- #243 — outbound webhooks: the workspace's own systems get told.
--
-- Everything this product does today stops at our three clients. A contractor
-- already runs a scheduling tool and an accounting package, and the only way a
-- solo team ships connectors for all of them is to not ship connectors at all:
-- ship the substrate and let the integrator build against it.
--
-- Outbound first, deliberately. #243's own devil's advocate is right that a
-- public API is permanent attack surface, and an outbound webhook grants NO new
-- inbound authority — it is a signed POST leaving the building. The scoped API
-- keys and the read/write surface land on top of this, not before it.
--
-- ## Why the secret is unreachable from a client key
--
-- `webhook_endpoints.secret` is the HMAC key the receiver checks. It has to be
-- readable by whatever signs the request, which is the Worker, and by nothing
-- else — a leaked `authenticated` key that can read it can forge our
-- signature on any payload it likes, which is precisely the property the
-- signature exists to deny. So neither table gets a policy and neither gets a
-- grant to `anon`/`authenticated`: the only path in is the Worker's
-- service_role, behind `/v1` authorization, and the secret leaves the building
-- exactly once, in the 201 that creates the endpoint.
--
-- ## Why the event vocabulary is NOT a check constraint
--
-- The subscribable event names live in `packages/shared` and are validated
-- there. Writing the same list again in SQL is the shape that has already cost
-- this repo three rounds (a per-client predicate that drifts): two lists, one
-- of which is authoritative and neither of which says so. The column is text;
-- the vocabulary has one home.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- Where a workspace wants to be told.
-- ---------------------------------------------------------------------------
create table public.webhook_endpoints (
  id           uuid primary key default gen_random_uuid(),
  company_id   uuid not null references public.companies(id) on delete restrict,
  -- The destination. https only, and enforced here rather than only in the
  -- route: this is a server-side fetch to a customer-controlled address, so
  -- the scheme is a security property (an http endpoint would carry the
  -- payload, which is customer data, in clear). The route additionally refuses
  -- private and loopback hosts — SSRF is the other half and it needs a host
  -- parser, which SQL is the wrong place for.
  url          text not null check (url like 'https://%' and length(url) between 12 and 2000),
  -- What the integrator calls this. Their label, not ours.
  description  text check (description is null or length(description) <= 200),
  -- The HMAC-SHA256 key. Generated by the Worker, shown once, never again.
  secret       text not null,
  -- Subscribed event names. An empty array is a subscription to nothing, which
  -- is a mistake rather than a preference, so it is refused.
  events       text[] not null check (cardinality(events) > 0),
  active       boolean not null default true,
  -- Set when WE turn it off, so the UI can say why rather than showing a
  -- toggle the customer flipped and we silently flipped back.
  disabled_reason text,
  disabled_at  timestamptz,
  consecutive_failures int not null default 0,
  last_success_at timestamptz,
  last_failure_at timestamptz,
  created_by   uuid references auth.users(id) on delete restrict,
  created_at   timestamptz not null default now()
);

create index webhook_endpoints_company_idx
  on public.webhook_endpoints (company_id);

-- The fan-out lookup on every emitted event: active endpoints for this
-- workspace subscribed to this name. GIN over the array so the `&&` containment
-- test does not degrade into a scan of every endpoint the workspace owns.
create index webhook_endpoints_events_idx
  on public.webhook_endpoints using gin (events);

alter table public.webhook_endpoints enable row level security;
revoke all on table public.webhook_endpoints
  from public, anon, authenticated, service_role;
grant select, insert, update, delete on table public.webhook_endpoints
  to service_role;

-- ---------------------------------------------------------------------------
-- Every attempt, and what the far end said about it.
--
-- This is both the retry queue and the delivery log the customer inspects.
-- One table rather than two because they are the same rows read two ways, and
-- a separate log written alongside a separate queue is a consistency problem
-- nobody needs: the row that is retrying IS the row they are looking at.
-- ---------------------------------------------------------------------------
create table public.webhook_deliveries (
  id           uuid primary key default gen_random_uuid(),
  company_id   uuid not null references public.companies(id) on delete restrict,
  endpoint_id  uuid not null references public.webhook_endpoints(id) on delete cascade,
  event_type   text not null,
  -- The exact bytes we signed, kept so a redelivery re-sends the event as it
  -- was rather than as the world is now. A webhook that quietly changes its
  -- mind between attempts is unusable for reconciliation.
  payload      jsonb not null,
  status       text not null default 'pending'
                 check (status in ('pending', 'delivering', 'succeeded', 'failed')),
  attempts     int not null default 0,
  next_attempt_at timestamptz not null default now(),
  -- What came back. `response_status` is the far end's HTTP code;
  -- `last_error` is OUR description of the failure (timeout, DNS, non-2xx).
  -- Neither ever carries the customer's message content: #513's lesson is that
  -- an error string built from a decode failure smuggles the field's VALUE
  -- into a place with different access rules. The payload column is the one
  -- place the content lives, and it is tenant-scoped like everything else.
  response_status int,
  last_error   text,
  created_at   timestamptz not null default now(),
  delivered_at timestamptz
);

create index webhook_deliveries_company_idx
  on public.webhook_deliveries (company_id, created_at desc);

-- The sweeper's claim: due, not yet terminal. Partial so the index stays the
-- size of the backlog rather than the size of the history.
create index webhook_deliveries_due_idx
  on public.webhook_deliveries (next_attempt_at)
  where status in ('pending', 'delivering');

create index webhook_deliveries_endpoint_idx
  on public.webhook_deliveries (endpoint_id, created_at desc);

alter table public.webhook_deliveries enable row level security;
revoke all on table public.webhook_deliveries
  from public, anon, authenticated, service_role;
grant select, insert, update, delete on table public.webhook_deliveries
  to service_role;

-- ---------------------------------------------------------------------------
-- A workspace may not own an unbounded number of endpoints.
--
-- Not a style rule — a cost one. Every endpoint multiplies every event into
-- another outbound subrequest, and the workspace that adds two hundred of them
-- is spending our egress and our CPU on their loop. Ten is well past what an
-- integration list needs and far short of what hurts.
-- ---------------------------------------------------------------------------
create or replace function public.enforce_webhook_endpoint_cap()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_count int;
begin
  select count(*) into v_count
    from public.webhook_endpoints
   where company_id = new.company_id;
  if v_count >= 10 then
    raise exception 'webhook endpoint cap reached for company %', new.company_id
      using errcode = 'check_violation';
  end if;
  return new;
end $$;

revoke execute on function public.enforce_webhook_endpoint_cap()
  from public, anon, authenticated;

create trigger webhook_endpoints_cap
  before insert on public.webhook_endpoints
  for each row execute function public.enforce_webhook_endpoint_cap();

-- ---------------------------------------------------------------------------
-- Claim due deliveries, exactly once.
--
-- The sweeper runs every five minutes and a slow run overlaps the next tick.
-- A read-then-update would hand both ticks the same rows and send the customer
-- the same event twice, which is the one thing a delivery log must not do on
-- its own account. `for update skip locked` is the same guarded-claim idiom as
-- `api_claim_contact_message`: the second caller sees the rows as taken rather
-- than blocking behind the first.
--
-- Claiming also STAMPS the attempt (`attempts + 1`, status `delivering`), so a
-- run that dies mid-flight leaves a row that is visibly in-flight and past due
-- rather than one that looks fresh. The reaper below is what un-sticks those.
-- ---------------------------------------------------------------------------
create or replace function public.api_claim_webhook_deliveries(p_limit int default 50)
returns setof public.webhook_deliveries
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_limit is null or p_limit <= 0 or p_limit > 500 then
    raise exception 'api_claim_webhook_deliveries: p_limit must be between 1 and 500';
  end if;

  return query
  with due as (
    select d.id
      from public.webhook_deliveries d
     where d.status in ('pending', 'delivering')
       and d.next_attempt_at <= now()
     order by d.next_attempt_at
     limit p_limit
     for update skip locked
  )
  update public.webhook_deliveries d
     set status = 'delivering',
         attempts = d.attempts + 1,
         -- Held off far enough that a run which dies mid-flight does not get
         -- re-claimed by the very next tick while the first POST may still be
         -- in the air. The real backoff is written by the delivering code on
         -- the way out; this is only the crash floor.
         next_attempt_at = now() + interval '15 minutes'
    from due
   where d.id = due.id
  returning d.*;
end $$;

revoke execute on function public.api_claim_webhook_deliveries(int)
  from public, anon, authenticated;
grant execute on function public.api_claim_webhook_deliveries(int) to service_role;

-- ---------------------------------------------------------------------------
-- The delivery log does not keep customer content forever.
--
-- `webhook_deliveries.payload` is the same class of data as `webhook_events`:
-- message bodies, phone numbers, contact names — copied out of the tables that
-- already have a retention answer, into one that would not. A log kept for
-- debugging is worth thirty days; after that it is a second copy of the
-- workspace's most sensitive content whose only defence is that nobody has
-- looked at it.
--
-- Batched and idempotent, in the shape the other retention prunes use, so the
-- daily cron can call it repeatedly without a long-running delete.
-- ---------------------------------------------------------------------------
create or replace function public.api_prune_webhook_deliveries(p_limit int default 5000)
returns int
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_deleted int;
begin
  if p_limit is null or p_limit <= 0 then
    raise exception 'api_prune_webhook_deliveries: p_limit must be > 0';
  end if;

  delete from public.webhook_deliveries
   where ctid in (
     select ctid from public.webhook_deliveries
      where created_at < now() - interval '30 days'
      limit p_limit
   );
  get diagnostics v_deleted = row_count;
  return v_deleted;
end $$;

revoke execute on function public.api_prune_webhook_deliveries(int)
  from public, anon, authenticated;
grant execute on function public.api_prune_webhook_deliveries(int) to service_role;

-- ---------------------------------------------------------------------------
-- The workspace teardown has to reach both new tables.
--
-- `purge_workspace.test.sql` derives the expected set from the catalogue, so
-- this is not a follow-up — it is the same change as creating the tables. Body
-- copied forward from 20260814000000 with the two names added; a `create or
-- replace` that re-derives the list from memory is how a table silently stops
-- being erased.
--
-- Ordering: `webhook_deliveries` before `webhook_endpoints`, which it
-- references. The cascade would handle it, but the loop deletes in batches and
-- returns after the first table that yields rows — leaving the parent for a
-- later step means the child is gone by the time we get there either way, and
-- the explicit order is what makes that true rather than incidental.
-- ---------------------------------------------------------------------------
create or replace function public.purge_workspace_step(
  p_company_id uuid,
  p_limit      int default 500
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_tables text[] := array[
    'usage_events', 'tasks', 'message_mentions', 'message_attachments',
    'attachments',
    'conversation_summaries',
    -- #224: before `messages` and `conversations`, both of which it references.
    'payment_requests',
    'messages', 'conversation_events', 'conversations',
    'call_records', 'calls', 'port_requests', 'text_enablement_orders',
    'contacts', 'phone_numbers',
    'template_uses',
    'tags',
    'templates', 'invites', 'messaging_registrations', 'grace_notices',
    'inbound_notification_days', 'usage_alerts', 'egress_events', 'audit_log',
    'company_members',
    'call_member_legs', 'company_ai_settings', 'company_ai_usage',
    'company_modules', 'email_ledger', 'member_telephony_credentials',
    'notification_prefs', 'notification_read_items', 'notification_reads',
    'number_access', 'outbound_call_authorizations', 'outbound_dial_leases',
    'activation_stall_state', 'appointment_reminder_rules', 'billing_disputes',
    'blocked_senders', 'call_silence_state', 'cancellation_reasons',
    'contact_field_defs', 'data_exports', 'feature_flag_overrides',
    'high_priority_push_budget', 'high_priority_push_days', 'lead_sources',
    'number_port_outs', 'ownership_confirmations', 'ownership_transfers',
    'prepayments', 'public_links', 'referrals', 'retention_notices',
    'saved_views',
    -- #224: the Stripe account mirror. The account itself is NOT deleted at
    -- Stripe by this — it is the business's own legal entity with their own
    -- payout history, and deleting it would destroy records they are required
    -- to keep. What goes is our copy of it.
    'stripe_connect_accounts',
    'voicemail_greetings',
    'provider_costs',
    -- #232: one row per code texted to a website visitor. Carries a phone
    -- number and an IP, so it goes with the workspace like everything else.
    'widget_verifications',
    -- #243: the delivery log carries the payloads we sent out, which is the
    -- workspace's own message and contact content. The child goes first.
    'webhook_deliveries', 'webhook_endpoints'
  ];
  v_table text;
  v_deleted int;
begin
  if p_limit is null or p_limit <= 0 then
    raise exception 'purge_workspace_step: p_limit must be > 0';
  end if;
  if not exists (
    select 1 from public.companies
     where id = p_company_id
       and deleted_at is not null
       and purge_after is not null
       and purge_after <= now()
  ) then
    raise exception 'purge_workspace_step: % is not past its purge window', p_company_id;
  end if;

  foreach v_table in array v_tables loop
    execute format(
      'delete from public.%I where ctid in (
         select ctid from public.%I where company_id = $1 limit $2
       )', v_table, v_table)
      using p_company_id, p_limit;
    get diagnostics v_deleted = row_count;
    if v_deleted > 0 then
      return jsonb_build_object('step', v_table, 'deleted', v_deleted, 'done', false);
    end if;
  end loop;

  return jsonb_build_object('step', null, 'deleted', 0, 'done', true);
end $$;

-- Restated because a `create or replace` does NOT preserve them: dropping and
-- recreating a function hands it back the default PUBLIC execute grant that
-- anon and authenticated inherit.
revoke execute on function public.purge_workspace_step(uuid, int)
  from public, anon, authenticated;
grant execute on function public.purge_workspace_step(uuid, int) to service_role;
