import Foundation
import MetricKit

/// #485 — crash capture on the platform that had none.
///
/// # Why this is MetricKit and not a signal handler
///
/// The obvious port of Android's `CrashDiagnostics.kt` is
/// `NSSetUncaughtExceptionHandler`, and it would have been close to a no-op.
/// It catches Objective-C exceptions only, and the crashes Swift code actually
/// produces are not exceptions — a force-unwrapped nil, an index out of range,
/// a `fatalError`, an integer overflow are all TRAPS. Every one raises
/// SIGILL/SIGTRAP and never reaches an exception handler. Shipping that alone
/// would have added a settings row, looked complete, and caught approximately
/// none of this app's real crashes — worse than the honest nothing it
/// replaced, because it would have been believed.
///
/// Real coverage without a third party means signal handlers, and those are
/// the one piece of code that cannot be debugged by adding logging to it: a
/// handler that allocates, deadlocks or itself crashes turns every crash into
/// a hang. That risk is unacceptable in a repo where Swift compiles only in
/// CI and nobody here can run the result.
///
/// `MXCrashDiagnostic` is Apple's own crash reporter, which already catches
/// those signals correctly and hands us the result. So it gives full trap
/// coverage with no signal code of ours, and — the part that decided it — the
/// payload never leaves the device unless a person taps share. That is the
/// posture Android chose deliberately, and it means no new subprocessor, no
/// `/legal/subprocessors` row and no DATA-INVENTORY entry, which Crashlytics
/// would all have required.
///
/// # The honest cost
///
/// TIMELINESS. Apple decides when a payload is delivered; it is typically the
/// next launch after the crash but the system does not promise that, and it
/// can be up to a day. Android's report is on disk before the process dies.
/// The Diagnostics screen says so rather than implying parity — a crash list
/// that looks empty right after a crash would otherwise read as "the capture
/// is broken" when it means "Apple has not handed it over yet".
///
/// Objective-C exceptions are covered SEPARATELY by
/// ``installExceptionHandler()``, which is safe here precisely because an
/// uncaught-exception handler is not a signal context — it may allocate. It
/// is a supplement, not the mechanism: on its own it would be the trap that
/// this docblock exists to warn about.
///
/// # What is stored
///
/// Stack frames and device metadata, straight from Apple's payload. No
/// customer content, and nothing this app puts there — the payload is
/// generated by the OS, not assembled by us (SPEC §10).

/// One captured crash, as much of it as is worth keeping.
struct CrashReport: Codable, Identifiable, Equatable, Sendable {
    let id: UUID
    /// When the report was RECEIVED, not when the crash happened — Apple does
    /// not always say the latter, and a receipt time we actually know beats a
    /// crash time we would have to invent.
    let receivedAt: Date
    /// The app version the crash happened in, from the payload's metadata.
    /// Often NOT the version now installed, which is the whole point of
    /// keeping it.
    let appVersion: String?
    /// Apple's termination reason, e.g. "Namespace SIGNAL, Code 5". The one
    /// line that says whether this was a trap, a watchdog kill or an OOM.
    let reason: String?
    /// The signal, when there was one.
    let signal: String?
    /// The call stack, already text. Truncated — see ``CrashReportStore``.
    let stack: String

    init(
        id: UUID = UUID(),
        receivedAt: Date = Date(),
        appVersion: String?,
        reason: String?,
        signal: String?,
        stack: String
    ) {
        self.id = id
        self.receivedAt = receivedAt
        self.appVersion = appVersion
        self.reason = reason
        self.signal = signal
        self.stack = stack
    }
}

/// The pure half: rotation and clamping, with no MetricKit and no file system
/// in sight, so it can be tested without either.
enum CrashReportLog {
    /// Keep the last N. Matches Android's #197 ceiling for the same reason: a
    /// person who declines the prompt has not thrown the report away, and a
    /// list of one is a list that loses the interesting crash to the boring
    /// one that followed it.
    static let maxEntries = 20

    /// A stack longer than this is truncated. A crash report is read by a
    /// human pasting it into a message; the frames that matter are at the top,
    /// and an unbounded string here is a file that grows without limit on a
    /// device that is already having a bad day.
    static let maxStackCharacters = 8_000

    static func clampStack(_ stack: String) -> String {
        guard stack.count > maxStackCharacters else { return stack }
        return String(stack.prefix(maxStackCharacters)) + "\n… truncated"
    }

    /// Newest first, capped. Newest first because the screen shows the top of
    /// this list and the interesting crash is the one that just happened.
    static func merged(
        existing: [CrashReport],
        incoming: [CrashReport]
    ) -> [CrashReport] {
        (incoming + existing)
            .sorted { $0.receivedAt > $1.receivedAt }
            .prefix(maxEntries)
            .map { $0 }
    }
}

/// The impure half: a never-throwing shell over one JSON file.
///
/// Never-throwing on purpose. This runs while the app is starting up after a
/// crash, and a diagnostics store that can itself fail the launch is a worse
/// bug than the one it was built to explain.
enum CrashReportStore {
    private static let lock = NSLock()

    private static var url: URL? {
        guard
            let dir = FileManager.default.urls(
                for: .applicationSupportDirectory,
                in: .userDomainMask
            ).first
        else { return nil }
        try? FileManager.default.createDirectory(
            at: dir,
            withIntermediateDirectories: true
        )
        return dir.appendingPathComponent("crash-reports.json")
    }

    static func all() -> [CrashReport] {
        lock.lock()
        defer { lock.unlock() }
        return loadLocked()
    }

    static func append(_ reports: [CrashReport]) {
        guard !reports.isEmpty else { return }
        lock.lock()
        defer { lock.unlock() }
        let merged = CrashReportLog.merged(existing: loadLocked(), incoming: reports)
        saveLocked(merged)
    }

    static func clear() {
        lock.lock()
        defer { lock.unlock() }
        saveLocked([])
    }

    private static func loadLocked() -> [CrashReport] {
        guard let url, let data = try? Data(contentsOf: url) else { return [] }
        return (try? JSONDecoder().decode([CrashReport].self, from: data)) ?? []
    }

    private static func saveLocked(_ reports: [CrashReport]) {
        guard let url, let data = try? JSONEncoder().encode(reports) else { return }
        try? data.write(to: url, options: .atomic)
    }
}

/// The previously-installed handler, held at file scope rather than captured.
///
/// `NSSetUncaughtExceptionHandler` takes a C function pointer, and a Swift
/// closure converts to one ONLY if it captures nothing. So chaining cannot be
/// done by holding the old handler in a local — it has to be reachable as a
/// global. Chaining matters: ours is not the only handler an app may want, and
/// swallowing somebody else's is the kind of breakage that stays invisible
/// until the day it would have mattered.
private nonisolated(unsafe) var previousExceptionHandler:
    (@convention(c) (NSException) -> Void)?

/// Receives Apple's payloads and turns them into stored reports.
///
/// A singleton because `MXMetricManager` holds subscribers weakly and a
/// subscriber that gets deallocated silently stops receiving — which would
/// look exactly like "no crashes have happened".
// `@unchecked Sendable`: MetricKit may deliver on a background queue, and the
// only state this holds is a lock-guarded file. There is nothing for the
// compiler to verify and nothing for it to protect.
final class CrashDiagnostics: NSObject, MXMetricManagerSubscriber, @unchecked Sendable {
    static let shared = CrashDiagnostics()

    /// Subscribe, and install the Objective-C supplement. Call once, at launch.
    static func start() {
        MXMetricManager.shared.add(shared)
        installExceptionHandler()
    }

    func didReceive(_ payloads: [MXDiagnosticPayload]) {
        let reports = payloads.flatMap { payload in
            (payload.crashDiagnostics ?? []).map(Self.report(from:))
        }
        CrashReportStore.append(reports)
    }

    /// Metrics are not diagnostics — this app asks for neither, and the
    /// protocol requires the method. Implemented empty rather than omitted so
    /// the reason is written down instead of looking like an oversight.
    func didReceive(_ payloads: [MXMetricPayload]) {}

    static func report(from diagnostic: MXCrashDiagnostic) -> CrashReport {
        let meta = diagnostic.metaData
        return CrashReport(
            appVersion: meta.applicationBuildVersion,
            reason: diagnostic.terminationReason,
            signal: diagnostic.signal.map { "SIG\($0.intValue)" },
            stack: CrashReportLog.clampStack(
                String(
                    data: diagnostic.callStackTree.jsonRepresentation(),
                    encoding: .utf8
                ) ?? "(call stack unavailable)"
            )
        )
    }

    /// The Objective-C half, and ONLY that half.
    ///
    /// Safe to write a file from: an uncaught-exception handler runs in normal
    /// context, unlike a signal handler, so it may allocate. It catches
    /// exceptions thrown by UIKit and Foundation internals — a real class, and
    /// a small one in a Swift app. Swift's own traps do not come through here
    /// and never will; they arrive via MetricKit or not at all.
    ///
    /// Chained, so anything already installed still runs. Ours is not the only
    /// handler an app may want, and swallowing somebody else's is the kind of
    /// breakage that is invisible until the day it matters.
    private static func installExceptionHandler() {
        previousExceptionHandler = NSGetUncaughtExceptionHandler()
        NSSetUncaughtExceptionHandler { exception in
            CrashReportStore.append([
                CrashReport(
                    appVersion: Bundle.main.object(
                        forInfoDictionaryKey: "CFBundleVersion"
                    ) as? String,
                    reason: exception.name.rawValue,
                    signal: nil,
                    stack: CrashReportLog.clampStack(
                        exception.callStackSymbols.joined(separator: "\n")
                    )
                ),
            ])
            previousExceptionHandler?(exception)
        }
    }
}
