// AUTOGENERATED by apps/web/scripts/build-photos.mjs. Do not edit by hand.
//
// The JobText marketing photography set (DESIGN-DIRECTION §4). Real, authentic
// tradespeople / service-business photos from Unsplash (photographer-contributed,
// the FREE license: free commercial use, no attribution required). Every photo is
// re-graded to ONE consistent DUOTONE in the palette (petrol shadows #0B4F49 to
// paper highlights #E6EBE8) plus a whisper of grain, so the set reads as one
// owned frame language (not stock). Sources + photographers are recorded in
// public/img/CREDITS.md. To reproduce: node apps/web/scripts/build-photos.mjs.
//
// Each entry is pre-sized WebP + AVIF at two display widths (primary + small),
// with intrinsic width/height (zero CLS) and a tiny blur-up placeholder.
// Render through <Photo id="..."/> (components/marketing/photo.tsx).

export type Photo = {
  /** Primary WebP path under /public (the 1200px-wide variant). */
  readonly webp: string;
  /** Primary AVIF path under /public (same display size). */
  readonly avif: string;
  /** WebP srcset string across the emitted widths (small + primary). */
  readonly srcsetWebp: string;
  /** AVIF srcset string across the emitted widths. */
  readonly srcsetAvif: string;
  /** Intrinsic width of the primary variant (CSS px). */
  readonly w: number;
  /** Intrinsic height of the primary variant (CSS px). */
  readonly h: number;
  /** Blurred low-res placeholder as a base64 WebP data-URI (blur-up). */
  readonly blur: string;
  /** Honest alt text describing the photo. */
  readonly alt: string;
  /** Photographer + source, for the credits record. */
  readonly credit: string;
};

export const photos = {
  "plumber-pipe": {
    webp: "/img/plumber-pipe-1200.webp",
    avif: "/img/plumber-pipe-1200.avif",
    srcsetWebp: "/img/plumber-pipe-600.webp 600w, /img/plumber-pipe-1200.webp 1200w",
    srcsetAvif: "/img/plumber-pipe-600.avif 600w, /img/plumber-pipe-1200.avif 1200w",
    w: 1200,
    h: 900,
    blur: "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAADQAwCdASoUAA8APu1iqU2ppaOiMAgBMB2JQBfnBEB9r9ZcNJmmkWgA+T1lgZb/zCHBy0CSy7iqLkH2lOoviFNOSJ7ZAs8oc71VD7EoPTUQpj8nXELpEwOBjT2fYlB9GaU+LC0C57x1V75szji/chruliciiCtvvdf0ntuYD+C8QeHwyDcfFqAA",
    alt: "A plumber working on the pipes under a sink.",
    credit: "Photo by Timur Shakerzianov on Unsplash (https://unsplash.com/photos/c314Gh8dXAo)",
  },
  "plumber-heater": {
    webp: "/img/plumber-heater-1200.webp",
    avif: "/img/plumber-heater-1200.avif",
    srcsetWebp: "/img/plumber-heater-600.webp 600w, /img/plumber-heater-1200.webp 1200w",
    srcsetAvif: "/img/plumber-heater-600.avif 600w, /img/plumber-heater-1200.avif 1200w",
    w: 1200,
    h: 900,
    blur: "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAADwAwCdASoUAA8APu1iqU2ppaOiMAgBMB2JYwC06B6/pV8d7vQEc14AAP6EGsv90LvnzuRA52/h8S3Aqnlu9XhiKjK4Ck06gB7gtBk7UotAJarWWDoyD5LwEYPDL4w+tLrhe/6et2IbBRJPFwmqdkch7pykNAEeMS7AgLlTbuMXNQI8kTJ9T0s5FFf8RJMh/e6e4EnSSAAAAA==",
    alt: "A tradesperson servicing a water heater on a job.",
    credit: "Photo by Timur Shakerzianov on Unsplash (https://unsplash.com/photos/kxuz4YrLxSc)",
  },
  "tools-wall": {
    webp: "/img/tools-wall-1200.webp",
    avif: "/img/tools-wall-1200.avif",
    srcsetWebp: "/img/tools-wall-600.webp 600w, /img/tools-wall-1200.webp 1200w",
    srcsetAvif: "/img/tools-wall-600.avif 600w, /img/tools-wall-1200.avif 1200w",
    w: 1200,
    h: 900,
    blur: "data:image/webp;base64,UklGRsoAAABXRUJQVlA4IL4AAABwBACdASoUAA8APu1iqU2ppaOiMAgBMB2JYwDCgYu4qR9q7eK6iiuBa4T4QAD+lNjLGdld0tvJveSZ4Dw367MQP29uzJvtgq7kdsY2pN/2tDUQToKEa1v9opWAaQ2TbLe0ZmN0R1mHIrS1AxZVb1GkE3Z9qEyzqQwhdrkPgZ5gsR2UE3zKeQfFw8tCrUbEW1go/dQTfnw5K3Dt1e0oy23WenbS/LapJAa/+Ki8StX8mLq+/lTnKBpIHAA+2gAA",
    alt: "A tradesperson holding a tool in front of a wall of tools.",
    credit: "Photo by Anton Savinov on Unsplash (https://unsplash.com/photos/Cx5Lk7Rv-vE)",
  },
  "landscaper-shovel": {
    webp: "/img/landscaper-shovel-1200.webp",
    avif: "/img/landscaper-shovel-1200.avif",
    srcsetWebp: "/img/landscaper-shovel-600.webp 600w, /img/landscaper-shovel-1200.webp 1200w",
    srcsetAvif: "/img/landscaper-shovel-600.avif 600w, /img/landscaper-shovel-1200.avif 1200w",
    w: 1200,
    h: 900,
    blur: "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAADQAwCdASoUAA8APu1iqU2ppaOiMAgBMB2JYwAASgQF1RHcUzo+ZgAA9z6mZMeBh7efIRh2DWnLnPDhIhSTHFXl/vys5e943bOcwWwXZ696AVIFU6tnn+Np6Iee6E47IIhhuRn4G+rehH9B8XL88sTXZRPbKW3cwdR3Hn3iRFf3dvNjIbdYQQ0n8ORFAAAA",
    alt: "A landscaper digging in a yard with a shovel.",
    credit: "Photo by Jared Muller on Unsplash (https://unsplash.com/photos/EkhWxU_pgLo)",
  },
  "landscaper-mower": {
    webp: "/img/landscaper-mower-1200.webp",
    avif: "/img/landscaper-mower-1200.avif",
    srcsetWebp: "/img/landscaper-mower-600.webp 600w, /img/landscaper-mower-1200.webp 1200w",
    srcsetAvif: "/img/landscaper-mower-600.avif 600w, /img/landscaper-mower-1200.avif 1200w",
    w: 1200,
    h: 900,
    blur: "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAAAQBACdASoUAA8APu1iqU2ppaOiMAgBMB2JQBOmUABikhpnuzQBp6Y2AAD80O7dH+coKyibDjPzuKHLOePRw9eyvAGw1fCE1F7ca+dsr4WdUxH2kKb3lzynxsOvtN+qDjgelnIjJ3jb5U1tWIDm6Wq3QF3nWahcBWQBdIANQAA=",
    alt: "A lawn-care crew mowing a green lawn.",
    credit: "Photo by Michael Smith on Unsplash (https://unsplash.com/photos/bsld7GjQwjI)",
  },
  "gardener-hands": {
    webp: "/img/gardener-hands-1200.webp",
    avif: "/img/gardener-hands-1200.avif",
    srcsetWebp: "/img/gardener-hands-600.webp 600w, /img/gardener-hands-1200.webp 1200w",
    srcsetAvif: "/img/gardener-hands-600.avif 600w, /img/gardener-hands-1200.avif 1200w",
    w: 1200,
    h: 900,
    blur: "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAACwBACdASoUAA8APu1iqU2ppaOiMAgBMB2JQBfnO4FwTuBJ7mhvrQwVgTX9XbbAAP7w3FrM1rCMJ7WaTeOeul4O0isnuQU9vhAN0ZdlzgSHJdmcJ2h3O8XR3wijF8PovgjEBVngkB04TdCUqT9UHJSGjT8P44QPiR0vj4KU66X3a45f3lp7RW+NxVnX/j01FNWVrFvcAAA=",
    alt: "Gloved hands planting a seedling in soil.",
    credit: "Photo by Jonathan Kemper on Unsplash (https://unsplash.com/photos/CbZh3kaPxrE)",
  },
  "salon-stylist": {
    webp: "/img/salon-stylist-1200.webp",
    avif: "/img/salon-stylist-1200.avif",
    srcsetWebp: "/img/salon-stylist-600.webp 600w, /img/salon-stylist-1200.webp 1200w",
    srcsetAvif: "/img/salon-stylist-600.avif 600w, /img/salon-stylist-1200.avif 1200w",
    w: 1200,
    h: 900,
    blur: "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAABwBACdASoUAA8APu1iqU2ppaOiMAgBMB2JQBdmUI8DOg4WfsEsgjYV1cRmAAD+4dspFvnChzDnv1Pz2/1iLldlU5FN4qh3WMPzsLZD3+t7UnDZr9Zj+PpTfjqKI+5KfRXkAnHzf6qfy2LxYf7Xqzc5G9p0eZRj5U2fxla/9WKvLv021EKgpf5eoT5QlvkQetphSgAA",
    alt: "A salon stylist drying a client's hair.",
    credit: "Photo by Adam Winger on Unsplash (https://unsplash.com/photos/FkAZqQJTbXM)",
  },
  "salon-cut": {
    webp: "/img/salon-cut-1200.webp",
    avif: "/img/salon-cut-1200.avif",
    srcsetWebp: "/img/salon-cut-600.webp 600w, /img/salon-cut-1200.webp 1200w",
    srcsetAvif: "/img/salon-cut-600.avif 600w, /img/salon-cut-1200.avif 1200w",
    w: 1200,
    h: 900,
    blur: "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAAAwBACdASoUAA8APu1iqU2ppaOiMAgBMB2JQAXf+A2a5f/GKBOVWjY1odwA/tznfICRv4fqQITOivO5Zkw86Mmt2NoMo2XG9yEpWzriDjfhsHLN3yKe8zcgmdmFR+LKikU2T3TMNWXi8JzjiiXs0gr30/sOf9zd7S2aJf+wc7yxxWQHPykNGuizyyCYgZALRUmXOkcDXBgLkNTKs9h2IdJ42PIAAA==",
    alt: "A hairstylist cutting a client's hair with scissors.",
    credit: "Photo by Ionela Mat on Unsplash (https://unsplash.com/photos/lps3FolQ6Ro)",
  },
  "texting-hands": {
    webp: "/img/texting-hands-1200.webp",
    avif: "/img/texting-hands-1200.avif",
    srcsetWebp: "/img/texting-hands-600.webp 600w, /img/texting-hands-1200.webp 1200w",
    srcsetAvif: "/img/texting-hands-600.avif 600w, /img/texting-hands-1200.avif 1200w",
    w: 1200,
    h: 900,
    blur: "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAABQBACdASoUAA8APu1iqU2ppaOiMAgBMB2JQBfnMXDdn1uxqH/nXiqkJ5WwAPlu+wRclx1VpxlVg07jZDj/6zLbu4iBJLRzFxv8LTQwMZPksZkRsjuVGSGSXngxFQcYmAPlBDt2PiGoqFHU+173/WTd152FdaAqvuL1osi22v2Aog0FzI3IMULGqDlE8+8DMoD2mjrtSNvryUD+rlAfdngnfLPVRyAA",
    alt: "Close-up of hands texting on a smartphone.",
    credit: "Photo by Darya Ezerskaya on Unsplash (https://unsplash.com/photos/hgz7pZkQoQc)",
  },
  "phone-in-hand": {
    webp: "/img/phone-in-hand-1200.webp",
    avif: "/img/phone-in-hand-1200.avif",
    srcsetWebp: "/img/phone-in-hand-600.webp 600w, /img/phone-in-hand-1200.webp 1200w",
    srcsetAvif: "/img/phone-in-hand-600.avif 600w, /img/phone-in-hand-1200.avif 1200w",
    w: 1200,
    h: 900,
    blur: "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADQAwCdASoUAA8APu1iqU2ppaOiMAgBMB2JQBjeg+42UpydViio1gAA/uzsp0Hacd4Wv57U++3s66uzreHk6NSthyFYTM2OOjvDXudfzvPVmrhN0hwlHOQD4p8AAA==",
    alt: "A person reading a text on their smartphone.",
    credit: "Photo by Priscilla Du Preez on Unsplash (https://unsplash.com/photos/BjhUu6BpUZA)",
  },
  "owner-apron-phone": {
    webp: "/img/owner-apron-phone-1200.webp",
    avif: "/img/owner-apron-phone-1200.avif",
    srcsetWebp: "/img/owner-apron-phone-600.webp 600w, /img/owner-apron-phone-1200.webp 1200w",
    srcsetAvif: "/img/owner-apron-phone-600.avif 600w, /img/owner-apron-phone-1200.avif 1200w",
    w: 1200,
    h: 900,
    blur: "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAADwAwCdASoUAA8APu1iqU2ppaOiMAgBMB2JQBOgBCjz00WyfqDViW9AAP7jyI0oYo1hMP6b55iOj/eSMLfFa+IwpBSGZpg0gLceTZ07E+GUujPDU290hNTe8YkcDbmttGsumoNmPlKJYeOw0MJ7liT5BO1Bmh+u6JvtQ0G3K/+uGiKBnhbB2LB/mqEVQeZgH2E+zuj2GNUQAA==",
    alt: "A shop owner in an apron checking a text on his phone at the counter.",
    credit: "Photo by Ali Mkumbwa on Unsplash (https://unsplash.com/photos/uk3ey_vhDKA)",
  },
  "owner-counter-phone": {
    webp: "/img/owner-counter-phone-1200.webp",
    avif: "/img/owner-counter-phone-1200.avif",
    srcsetWebp: "/img/owner-counter-phone-600.webp 600w, /img/owner-counter-phone-1200.webp 1200w",
    srcsetAvif: "/img/owner-counter-phone-600.avif 600w, /img/owner-counter-phone-1200.avif 1200w",
    w: 1200,
    h: 900,
    blur: "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAABQBACdASoUAA8APu1iqU2ppaOiMAgBMB2JQAB8kDzwWkVy8gTwIHiLKAtAAP7VBH2PRUMidjICWvbnQtbNJr+o34uRbPwnZqEOsgONHGhjsUWLuTN+8QNXNTBpVLB0jcfcTG3RpaCwmOfFknmfzUVzPLky54cqfoPi5eGwZHLooOjk+OBMFi9v2L5PBbq2IZR+poAMUO/0GrC4oAA=",
    alt: "A small-business owner texting a customer from behind the counter.",
    credit: "Photo by Omar Lopez on Unsplash (https://unsplash.com/photos/iuBoZIZQkKM)",
  },
  "hvac-tech": {
    webp: "/img/hvac-tech-1200.webp",
    avif: "/img/hvac-tech-1200.avif",
    srcsetWebp: "/img/hvac-tech-600.webp 600w, /img/hvac-tech-1200.webp 1200w",
    srcsetAvif: "/img/hvac-tech-600.avif 600w, /img/hvac-tech-1200.avif 1200w",
    w: 1200,
    h: 900,
    blur: "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAABwBACdASoUAA8APu1iqU2ppaOiMAgBMB2JQBOmUAS3QfxlAzDLmjE3qnckAAD2v01db9Kbm29HCvdR6+V9FuRG2CMc5fDb5hcV18SD5773P08INHaQtCt0DwFSvdSlGnJvIJM59LZg/YNercHImNaGwBRbP8qhn8naSxVDAAA=",
    alt: "A service technician in a hard hat wiring an electrical panel.",
    credit: "Photo by Emmanuel Ikwuegbu on Unsplash (https://unsplash.com/photos/-0-kl1BjvFc)",
  },
  "crew-rooftop": {
    webp: "/img/crew-rooftop-1200.webp",
    avif: "/img/crew-rooftop-1200.avif",
    srcsetWebp: "/img/crew-rooftop-600.webp 600w, /img/crew-rooftop-1200.webp 1200w",
    srcsetAvif: "/img/crew-rooftop-600.avif 600w, /img/crew-rooftop-1200.avif 1200w",
    w: 1200,
    h: 900,
    blur: "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAAAwBACdASoUAA8APu1iqU2ppaOiMAgBMB2JQBdgO4FvSuE3qckDNbgF9WAAyXaRZ0jUY9K923tXe8dCX8SznEs+njJx6Og2EeqyGkT5Qtx+wOw6i/0ACzWAslTnLdJ5l3fN/w+dBRFEe6P0Sd506OMhpomxeRcY3rbELD/SBUopqdv1k0dIgz2Y7nn27Ut9Zi4CZ9KzzVmufBhR6XV3WYwE2AA=",
    alt: "A two-person crew working together on a rooftop HVAC install.",
    credit: "Photo by Singapore Stock Photos on Unsplash (https://unsplash.com/photos/iS5GDeLDk0E)",
  },
} as const satisfies Record<string, Photo>;

export type PhotoId = keyof typeof photos;

/** Resolve one photo by id, or undefined if the key is unknown. */
export function getPhoto(id: string): Photo | undefined {
  return (photos as Record<string, Photo>)[id];
}
