// AUTOGENERATED by apps/web/scripts/build-photos.mjs — do not edit by hand.
//
// The JobText marketing photography set (VISUALS-V2 §2). Warm, authentic
// tradespeople / service-business photos from Unsplash (photographer-contributed,
// the FREE license — free commercial use, no attribution required). One
// art-director warm grade is applied to the whole set by the build script so it
// reads as one shoot. Sources + photographers are recorded in
// public/img/CREDITS.md. To reproduce: node apps/web/scripts/build-photos.mjs.
//
// Each entry is pre-sized WebP + AVIF at two display widths (primary + small),
// with intrinsic width/height (zero CLS) and a tiny blur-up placeholder.
// Render through <Photo id="..."/> (components/marketing/photo.tsx).

export type Photo = {
  /** Primary WebP path under /public (the 1200px-wide variant). */
  readonly webp: string;
  /** Primary AVIF path under /public (same display size). */
  readonly avif: string;
  /** WebP srcset string across the emitted widths (small + primary). */
  readonly srcsetWebp: string;
  /** AVIF srcset string across the emitted widths. */
  readonly srcsetAvif: string;
  /** Intrinsic width of the primary variant (CSS px). */
  readonly w: number;
  /** Intrinsic height of the primary variant (CSS px). */
  readonly h: number;
  /** Blurred low-res placeholder as a base64 WebP data-URI (blur-up). */
  readonly blur: string;
  /** Honest alt text describing the photo. */
  readonly alt: string;
  /** Photographer + source, for the credits record. */
  readonly credit: string;
};

export const photos = {
  "plumber-pipe": {
    webp: "/img/plumber-pipe-1200.webp",
    avif: "/img/plumber-pipe-1200.avif",
    srcsetWebp: "/img/plumber-pipe-600.webp 600w, /img/plumber-pipe-1200.webp 1200w",
    srcsetAvif: "/img/plumber-pipe-600.avif 600w, /img/plumber-pipe-1200.avif 1200w",
    w: 1200,
    h: 900,
    blur: "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAAAwBQCdASoUAA8APu1iqU2ppaOiMAgBMB2JbACdMoR4PoM4DF1QHmwlW5hOOKSbb5JMKAD81zlcum7VqL9/l7jdrnwMIwCt4aO4k82V1qljJZZEW82QWR+HsTQBbHJTHdsIvSbLq7D6bS2QQ7GXZMrFR2w+WJtR5XeR0afgB3VH8xgnkVdJu7EwhMBzDpWnNOiW8v+tkbzAAA==",
    alt: "A plumber working on the pipes under a sink.",
    credit: "Photo by Timur Shakerzianov on Unsplash (https://unsplash.com/photos/c314Gh8dXAo)",
  },
  "plumber-heater": {
    webp: "/img/plumber-heater-1200.webp",
    avif: "/img/plumber-heater-1200.avif",
    srcsetWebp: "/img/plumber-heater-600.webp 600w, /img/plumber-heater-1200.webp 1200w",
    srcsetAvif: "/img/plumber-heater-600.avif 600w, /img/plumber-heater-1200.avif 1200w",
    w: 1200,
    h: 900,
    blur: "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAAAwBQCdASoUAA8APu1iqU2ppaOiMAgBMB2JbACdMoMYLI6VQAuE1cyxxV9V+qxjY7NgAAD+QTP/YcfzTR4+Bo8WuiwPEGVy2dlRjIM0RrX4R20Iarps4gMrUTrpvN8tYaBDJUz6wCJQTb0dtabmf1nXlai9e1sZQ4+umQAyQQ5zBdVGMbSyekJo1AgsI9eh1zgtn6tK892zrJpCB+ARqAMAAAA=",
    alt: "A tradesperson servicing a water heater on a job.",
    credit: "Photo by Timur Shakerzianov on Unsplash (https://unsplash.com/photos/kxuz4YrLxSc)",
  },
  "tools-wall": {
    webp: "/img/tools-wall-1200.webp",
    avif: "/img/tools-wall-1200.avif",
    srcsetWebp: "/img/tools-wall-600.webp 600w, /img/tools-wall-1200.webp 1200w",
    srcsetAvif: "/img/tools-wall-600.avif 600w, /img/tools-wall-1200.avif 1200w",
    w: 1200,
    h: 900,
    blur: "data:image/webp;base64,UklGRuIAAABXRUJQVlA4INYAAACQBACdASoUAA8APu1iqU2ppaOiMAgBMB2JbAC7LwCfHSItD8vIAFJYbLAvBQAA/sdrI0LRVdNZjEeixuT6qOQv9zmTUNP/7Aoqt6SEUI6uWVHLCfofQqi5EAw6vCwdR14xP7/Oe6cNUe2ktfnXjv4Vi/xvDaFoiau27gXeFIsEAH/gq3CYEB41zZSXYIxpq3o1IsyJjBOzYogixse3HrQfFZglWfiotrx9rOPeQvc7u2/zrVIUNNz/5OTP4NI5v53Y/14qP81038M/4Irf8m/fhC5jUAAA",
    alt: "A tradesperson holding a tool in front of a wall of tools.",
    credit: "Photo by Anton Savinov on Unsplash (https://unsplash.com/photos/Cx5Lk7Rv-vE)",
  },
  "landscaper-shovel": {
    webp: "/img/landscaper-shovel-1200.webp",
    avif: "/img/landscaper-shovel-1200.avif",
    srcsetWebp: "/img/landscaper-shovel-600.webp 600w, /img/landscaper-shovel-1200.webp 1200w",
    srcsetAvif: "/img/landscaper-shovel-600.avif 600w, /img/landscaper-shovel-1200.avif 1200w",
    w: 1200,
    h: 900,
    blur: "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAABQBACdASoUAA8APu1iqU2ppaOiMAgBMB2JZgC7LwABepdH7dE/kG+0sHAAAP6NiqeXf+EBE7Kg0NXkIniYUj/GdwPDhq5DbxGf78WMeTJNqFtSoDO4FncTlL3BY+vvVquzqcoF0DtzhG3Mtcq/L2Uw5xBuzgHbU5fIWYvkLd3v8YAA",
    alt: "A landscaper digging in a yard with a shovel.",
    credit: "Photo by Jared Muller on Unsplash (https://unsplash.com/photos/EkhWxU_pgLo)",
  },
  "landscaper-mower": {
    webp: "/img/landscaper-mower-1200.webp",
    avif: "/img/landscaper-mower-1200.avif",
    srcsetWebp: "/img/landscaper-mower-600.webp 600w, /img/landscaper-mower-1200.webp 1200w",
    srcsetAvif: "/img/landscaper-mower-600.avif 600w, /img/landscaper-mower-1200.avif 1200w",
    w: 1200,
    h: 900,
    blur: "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAACQAwCdASoUAA8APu1iqU2ppaOiMAgBMB2JZgCdAA86hKKYeBMsAMltgc1nJGA1n53FOKLuQYESlrTIU08VJjoj74daH9TO+TIK9J15rJg/P5m2vYTizoEQzWDWxdnxesUXFOPbwe1itxThan/Ejy0N7+PhuaKIGcEQTL6AAAA=",
    alt: "A lawn-care crew mowing a green lawn.",
    credit: "Photo by Michael Smith on Unsplash (https://unsplash.com/photos/bsld7GjQwjI)",
  },
  "gardener-hands": {
    webp: "/img/gardener-hands-1200.webp",
    avif: "/img/gardener-hands-1200.avif",
    srcsetWebp: "/img/gardener-hands-600.webp 600w, /img/gardener-hands-1200.webp 1200w",
    srcsetAvif: "/img/gardener-hands-600.avif 600w, /img/gardener-hands-1200.avif 1200w",
    w: 1200,
    h: 900,
    blur: "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAABQBACdASoUAA8APu1iqU2ppaOiMAgBMB2JbAC06YvCi55yyNlXrHKrwaYAAP7uoMqZe/uv+kYXGZPunbGYq8D+QPLdPtjPhNM946Bsu2pUrQHKwwzHENKkbq3833IdrgRZFqxKJwltJl4NxFfWrekLd77RX5VTLVYbuvvInNWmTofcs447Z6EwU+o3lnRLW9zQ6FoVsIZBAAAA",
    alt: "Gloved hands planting a seedling in soil.",
    credit: "Photo by Jonathan Kemper on Unsplash (https://unsplash.com/photos/CbZh3kaPxrE)",
  },
  "salon-stylist": {
    webp: "/img/salon-stylist-1200.webp",
    avif: "/img/salon-stylist-1200.avif",
    srcsetWebp: "/img/salon-stylist-600.webp 600w, /img/salon-stylist-1200.webp 1200w",
    srcsetAvif: "/img/salon-stylist-600.avif 600w, /img/salon-stylist-1200.avif 1200w",
    w: 1200,
    h: 900,
    blur: "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAAAwBACdASoUAA8APu1iqU2ppaOiMAgBMB2JQBOmUAS3Ig8EwmUTmjH/NMAA/uHbKReSpbxi/4k0fObYnvILmLW2P6sSZ34zs80CznE7QqlUWTVJGUItblzlkoFc+ODSqavog+7SYN636flEYeaeddfX9VpkfyUw+qOj7rx/R0V5JxlJdHFpit80fEc9YPqTVevDbWMCaLlZLly3fZ4CSAAA",
    alt: "A salon stylist drying a client's hair.",
    credit: "Photo by Adam Winger on Unsplash (https://unsplash.com/photos/FkAZqQJTbXM)",
  },
  "salon-cut": {
    webp: "/img/salon-cut-1200.webp",
    avif: "/img/salon-cut-1200.avif",
    srcsetWebp: "/img/salon-cut-600.webp 600w, /img/salon-cut-1200.webp 1200w",
    srcsetAvif: "/img/salon-cut-600.avif 600w, /img/salon-cut-1200.avif 1200w",
    w: 1200,
    h: 900,
    blur: "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAACQBACdASoUAA8APu1iqU2ppaOiMAgBMB2JYgCdMoAlwxWumTEZvGyi1P3eawAA/tDkrzCJblFRChjUjmwyEnrd5e3zMfLLQgjrKeVTxJ/Tn/do20Ys0bDaQYjibPmcmXztjypZwYSvXrfXyuY4UM7nueSmggds2lI8qwioYyM5m8bwP6kAd19L+LgYBnwcfLntx4r5guLqwfQt80RKrtMLEQAAAA==",
    alt: "A hairstylist cutting a client's hair with scissors.",
    credit: "Photo by Ionela Mat on Unsplash (https://unsplash.com/photos/lps3FolQ6Ro)",
  },
  "texting-hands": {
    webp: "/img/texting-hands-1200.webp",
    avif: "/img/texting-hands-1200.avif",
    srcsetWebp: "/img/texting-hands-600.webp 600w, /img/texting-hands-1200.webp 1200w",
    srcsetAvif: "/img/texting-hands-600.avif 600w, /img/texting-hands-1200.avif 1200w",
    w: 1200,
    h: 900,
    blur: "data:image/webp;base64,UklGRsIAAABXRUJQVlA4ILYAAAAwBQCdASoUAA8APu1iqU2ppaOiMAgBMB2JZgCdMoRwIr+G5mPNQghn6ejERCCzgt32wADieBFgtRm93qGT0Pbqr8GWm8U6AiB4dTPeM1VX/zgdFr9DUZVsI8FUcRV0i2IZPd2sQKIQQ60HgoLrRO5zNT9RQpu2QXxltf6zn0KHkGfOqdk1LyjalLcW6dP29Cn07Kq8g8CvFl7ZmmOWZ+0vNeQABOnevA0KLYsrLEphqUKIYRMAAA==",
    alt: "Close-up of hands texting on a smartphone.",
    credit: "Photo by Darya Ezerskaya on Unsplash (https://unsplash.com/photos/hgz7pZkQoQc)",
  },
  "phone-in-hand": {
    webp: "/img/phone-in-hand-1200.webp",
    avif: "/img/phone-in-hand-1200.avif",
    srcsetWebp: "/img/phone-in-hand-600.webp 600w, /img/phone-in-hand-1200.webp 1200w",
    srcsetAvif: "/img/phone-in-hand-600.avif 600w, /img/phone-in-hand-1200.avif 1200w",
    w: 1200,
    h: 900,
    blur: "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAACwAwCdASoUAA8APu1iqU2ppaOiMAgBMB2JZQCdABVHhzGiMbdsQAD+7OynH1QLGcHla0MT8gtKh/3l1ymFvTtHLAB5ne5FS9FtX3+Plej38rPCWVw2AAAA",
    alt: "A person reading a text on their smartphone.",
    credit: "Photo by Priscilla Du Preez on Unsplash (https://unsplash.com/photos/BjhUu6BpUZA)",
  },
  "owner-apron-phone": {
    webp: "/img/owner-apron-phone-1200.webp",
    avif: "/img/owner-apron-phone-1200.avif",
    srcsetWebp: "/img/owner-apron-phone-600.webp 600w, /img/owner-apron-phone-1200.webp 1200w",
    srcsetAvif: "/img/owner-apron-phone-600.avif 600w, /img/owner-apron-phone-1200.avif 1200w",
    w: 1200,
    h: 900,
    blur: "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAABQBACdASoUAA8APu1iqU2ppaOiMAgBMB2JZACdMoGv/gOnpMtWKLhCAQfiAP7Z//XpuqiS15VTLWpZZU9Cj2/jgmVKtaQGyjDyNtQ+nKi5LAU97HJohpRbEKLLCBT/UQGY10GWeuPnRbkGlQ8iYmR4cOK97sQj8bW/eZB4tu9JaqkHs7kIh4hLGJ0xVThkngYnkzXrJAdYAA==",
    alt: "A shop owner in an apron checking a text on his phone at the counter.",
    credit: "Photo by Ali Mkumbwa on Unsplash (https://unsplash.com/photos/uk3ey_vhDKA)",
  },
  "owner-counter-phone": {
    webp: "/img/owner-counter-phone-1200.webp",
    avif: "/img/owner-counter-phone-1200.avif",
    srcsetWebp: "/img/owner-counter-phone-600.webp 600w, /img/owner-counter-phone-1200.webp 1200w",
    srcsetAvif: "/img/owner-counter-phone-600.avif 600w, /img/owner-counter-phone-1200.avif 1200w",
    w: 1200,
    h: 900,
    blur: "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAACQBACdASoUAA8APu1iqU2ppaOiMAgBMB2JagCdMoAlvhZAUvLqKeNjKYW/N1gA/sXtFOuVmRQlby/FqNNtSpu3TUfeUoVItC7xamswlOyTHD2GkC+XxSRVWSYHPnkvy0FMzOpaU+yqBuj8zbKTuOlYn1SWzKQTd5DmNc6CbHHa1Q9nbSD3qYWezwSb211YOl6yLHCIcQ81+7OPfboAAA==",
    alt: "A small-business owner texting a customer from behind the counter.",
    credit: "Photo by Omar Lopez on Unsplash (https://unsplash.com/photos/iuBoZIZQkKM)",
  },
  "hvac-tech": {
    webp: "/img/hvac-tech-1200.webp",
    avif: "/img/hvac-tech-1200.avif",
    srcsetWebp: "/img/hvac-tech-600.webp 600w, /img/hvac-tech-1200.webp 1200w",
    srcsetAvif: "/img/hvac-tech-600.avif 600w, /img/hvac-tech-1200.avif 1200w",
    w: 1200,
    h: 900,
    blur: "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAAAQBACdASoUAA8APu1iqU2ppaOiMAgBMB2JYgCdABVbhoZHSpMjuBGsAAD2vXKDWHVGAfgXVvV+sgk6CAfroAD6Mpn7O3dAhE/lRm/Z8sJB+KFM2RWcbsazCvv1886jFsQ9JOInTNBfNIRusGJjcQ8GdxWC36BAIAA=",
    alt: "A service technician in a hard hat wiring an electrical panel.",
    credit: "Photo by Emmanuel Ikwuegbu on Unsplash (https://unsplash.com/photos/-0-kl1BjvFc)",
  },
  "crew-rooftop": {
    webp: "/img/crew-rooftop-1200.webp",
    avif: "/img/crew-rooftop-1200.avif",
    srcsetWebp: "/img/crew-rooftop-600.webp 600w, /img/crew-rooftop-1200.webp 1200w",
    srcsetAvif: "/img/crew-rooftop-600.avif 600w, /img/crew-rooftop-1200.avif 1200w",
    w: 1200,
    h: 900,
    blur: "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAABwBACdASoUAA8APu1iqU2ppaOiMAgBMB2JZQCw8agWwA2KSXSfAsPd8KPH0ADP+zVHTD0cVrcyOznz0vnBF/njpzUiJ7MJ5SbYFCIhUeOziRNfUqTCnFPuWFm61lGFyfWnVtVS2QRevwZHnRQ8/Q/1QuVza1wfDf8pImUAtIx+pTlv40nX6ceXOjIXAcQA",
    alt: "A two-person crew working together on a rooftop HVAC install.",
    credit: "Photo by Singapore Stock Photos on Unsplash (https://unsplash.com/photos/iS5GDeLDk0E)",
  },
} as const satisfies Record<string, Photo>;

export type PhotoId = keyof typeof photos;

/** Resolve one photo by id, or undefined if the key is unknown. */
export function getPhoto(id: string): Photo | undefined {
  return (photos as Record<string, Photo>)[id];
}
